{{- if or (ne .Values.keyManager.awsKMS.accessKeyID "") (ne .Values.keyManager.awsKMS.secretAccessKey "") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spire-server.fullname" . }}-aws-kms
  namespace: {{ include "spire-server.namespace" . }}
data:
  {{- if ne .Values.keyManager.awsKMS.accessKeyID "" }}
  AWS_KMS_ACCESS_KEY_ID: {{ .Values.keyManager.awsKMS.accessKeyID | b64enc }}
  {{- end }}
  {{- if ne .Values.keyManager.awsKMS.secretAccessKey "" }}
  AWS_KMS_SECRET_ACCESS_KEY: {{ .Values.keyManager.awsKMS.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}
